//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportWebServiceForLocalBC
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ReportWebService", ConfigurationName="ReportWebServiceForLocalBC.ReportWebService_Port")]
    public interface ReportWebService_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/ReportWebService:GenerateReport", ReplyAction="*")]
        System.Threading.Tasks.Task<ReportWebServiceForLocalBC.GenerateReport_Result> GenerateReportAsync(ReportWebServiceForLocalBC.GenerateReport request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReport", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ReportWebService", IsWrapped=true)]
    public partial class GenerateReport
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ReportWebService", Order=0)]
        public int reportNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ReportWebService", Order=1)]
        public string parameters;
        
        public GenerateReport()
        {
        }
        
        public GenerateReport(int reportNo, string parameters)
        {
            this.reportNo = reportNo;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerateReport_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/ReportWebService", IsWrapped=true)]
    public partial class GenerateReport_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/ReportWebService", Order=0)]
        public string return_value;
        
        public GenerateReport_Result()
        {
        }
        
        public GenerateReport_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ReportWebService_PortChannel : ReportWebServiceForLocalBC.ReportWebService_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ReportWebService_PortClient : System.ServiceModel.ClientBase<ReportWebServiceForLocalBC.ReportWebService_Port>, ReportWebServiceForLocalBC.ReportWebService_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportWebService_PortClient() : 
                base(ReportWebService_PortClient.GetDefaultBinding(), ReportWebService_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ReportWebService_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportWebService_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), ReportWebService_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportWebService_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportWebService_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportWebService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportWebServiceForLocalBC.GenerateReport_Result> ReportWebServiceForLocalBC.ReportWebService_Port.GenerateReportAsync(ReportWebServiceForLocalBC.GenerateReport request)
        {
            return base.Channel.GenerateReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportWebServiceForLocalBC.GenerateReport_Result> GenerateReportAsync(int reportNo, string parameters)
        {
            ReportWebServiceForLocalBC.GenerateReport inValue = new ReportWebServiceForLocalBC.GenerateReport();
            inValue.reportNo = reportNo;
            inValue.parameters = parameters;
            return ((ReportWebServiceForLocalBC.ReportWebService_Port)(this)).GenerateReportAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportWebService_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReportWebService_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://win-2ajr95f2ai3:7047/ERPDEVBC140/WS/APSCL/Codeunit/ReportWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReportWebService_PortClient.GetBindingForEndpoint(EndpointConfiguration.ReportWebService_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReportWebService_PortClient.GetEndpointAddress(EndpointConfiguration.ReportWebService_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            ReportWebService_Port,
        }
    }
}
