//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", ConfigurationName="ServiceReference2.CustomerBill_Port")]
    public interface CustomerBill_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CustomerBill:BillGeneration", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.BillGeneration_Result> BillGenerationAsync(ServiceReference2.BillGeneration request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/CustomerBill:Greeting", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference2.Greeting_Result> GreetingAsync(ServiceReference2.Greeting request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillGeneration", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", IsWrapped=true)]
    public partial class BillGeneration
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", Order=1)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", Order=2)]
        public string month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", Order=3)]
        public decimal amount;
        
        public BillGeneration()
        {
        }
        
        public BillGeneration(string name, int year, string month, decimal amount)
        {
            this.name = name;
            this.year = year;
            this.month = month;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BillGeneration_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", IsWrapped=true)]
    public partial class BillGeneration_Result
    {
        
        public BillGeneration_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Greeting", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", IsWrapped=true)]
    public partial class Greeting
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", Order=0)]
        public string name;
        
        public Greeting()
        {
        }
        
        public Greeting(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Greeting_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", IsWrapped=true)]
    public partial class Greeting_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/CustomerBill", Order=0)]
        public string return_value;
        
        public Greeting_Result()
        {
        }
        
        public Greeting_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CustomerBill_PortChannel : ServiceReference2.CustomerBill_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CustomerBill_PortClient : System.ServiceModel.ClientBase<ServiceReference2.CustomerBill_Port>, ServiceReference2.CustomerBill_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerBill_PortClient() : 
                base(CustomerBill_PortClient.GetDefaultBinding(), CustomerBill_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomerBill_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerBill_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerBill_PortClient.GetBindingForEndpoint(endpointConfiguration), CustomerBill_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerBill_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerBill_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerBill_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerBill_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerBill_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.BillGeneration_Result> ServiceReference2.CustomerBill_Port.BillGenerationAsync(ServiceReference2.BillGeneration request)
        {
            return base.Channel.BillGenerationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.BillGeneration_Result> BillGenerationAsync(string name, int year, string month, decimal amount)
        {
            ServiceReference2.BillGeneration inValue = new ServiceReference2.BillGeneration();
            inValue.name = name;
            inValue.year = year;
            inValue.month = month;
            inValue.amount = amount;
            return ((ServiceReference2.CustomerBill_Port)(this)).BillGenerationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.Greeting_Result> ServiceReference2.CustomerBill_Port.GreetingAsync(ServiceReference2.Greeting request)
        {
            return base.Channel.GreetingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Greeting_Result> GreetingAsync(string name)
        {
            ServiceReference2.Greeting inValue = new ServiceReference2.Greeting();
            inValue.name = name;
            return ((ServiceReference2.CustomerBill_Port)(this)).GreetingAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerBill_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomerBill_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://win-jhhr4oovksp:7047/POWERDIVERPSERVICE/WS/APSCL/Codeunit/CustomerBill");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerBill_PortClient.GetBindingForEndpoint(EndpointConfiguration.CustomerBill_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerBill_PortClient.GetEndpointAddress(EndpointConfiguration.CustomerBill_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomerBill_Port,
        }
    }
}
